CmsShop/CmsShop/Controllers/CartController.cs
using CmsShop.Models.Data;
using CmsShop.Models.ViewModels.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace CmsShop.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            //initialization Cart
            //if Seesion exist  we assign value as List<CartVM>  else we create  new List<CartVM>();  
            var cart = Session["cart"] as List<CartVM> ?? new List<CartVM>(); 

            //chceck if cart is empty
            if(cart.Count == 0 || Session["cart"] == null)
            {
                ViewBag.Message = "Twój koszyk jest pusty";
            }
            //else..
            //Sum value of assume cart and redirect value to viewBag
            decimal total = 0;

            foreach (var item in cart)
            {
                total += item.Total;
            }

            ViewBag.GrandTotal = total;

            return View(cart);
        }


        //Create Cart in partial view
        public ActionResult CartPartial()
        {
            //initialization cartVM
            CartVM model = new CartVM();

            //initializaction quantity and price
            int quantity = 0;
            decimal price = 0;

            //check if the cart is save in session?
            if(Session["cart"] != null)
            {
                //fetch value from (existing)Session
                var list = (List<CartVM>)Session["cart"];

                foreach (var item in list)
                {
                    //sum value from session
                    quantity += item.Quantity;
                    price += item.Quantity * item.Price;

                }

                model.Quantity = quantity;
                model.Price = price;
            }
            //if session is empty
            else
            {
                //set zero for quantity and price
                quantity = 0;
                price = 0m;
            }

            return PartialView(model);
        }

        public ActionResult AddToCartPartial(int id)
        {
            //initualization CartVM List
            List<CartVM> cart = Session["cart"] as List<CartVM> ?? new List<CartVM>();
            //initializatiom  cartVM
            CartVM model = new CartVM();

            using(Db db = new Db())
            {
                //fetch product
                ProductDTO product = db.Products.Find(id);
                //check existng product in Cart
                var productInCart = cart.FirstOrDefault(x => x.ProductId == id);
                //In depend of if the product is in Cart, we Add product to cart or increment Quantity
                if (productInCart == null)
                {
                    cart.Add(new CartVM()
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        Quantity = 1,
                        Price = product.Price,
                        Image = product.ImageName
                    }); 
                }
                else  //product exist in cart
                {
                    productInCart.Quantity++;
                }
            }

            //fetch sum of values for quantity and price
            int quantity = 0;
            decimal price = 0m;

            foreach (var item in cart)
            {
                quantity += item.Quantity;
                price += item.Quantity * item.Price;
            }

            //set value at the model
            model.Quantity = quantity;
            model.Price = price;

            //save in seesion
            Session["cart"] = cart;

          

            return PartialView(model);
        }

        //increment quantity product(s) in Cart
        public JsonResult IncrementProduct(int productId)
        {
            //init list
            List<CartVM> cart = Session["cart"] as List<CartVM>;
            //fetch cartVm
            CartVM model = cart.FirstOrDefault(x => x.ProductId == productId);

            //increment quantity od product
            model.Quantity++;

            //prepatre json data 
            var result = new { qty = model.Quantity, price = model.Price };

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        //Decrement  quantity product(s) in Cart
        public ActionResult DecrementProduct(int productId)
        {

            //init list
            List<CartVM> cart = Session["cart"] as List<CartVM>;
            //fetch cartVm
            CartVM model = cart.FirstOrDefault(x => x.ProductId == productId);

            //Decrement quantity od product
            if(model.Quantity > 1)
            {
                //decrement if more than zero
                model.Quantity--;
            }

            else
            {
                //if zero == zero
                model.Quantity = 0;
                //remov product from cart
                cart.Remove(model);
            }
            

            //prepatre json data 
            var result = new { qty = model.Quantity, price = model.Price };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public void RemoveProduct(int productId)
        {
            //init list
            List<CartVM> cart = Session["cart"] as List<CartVM>;
            //fetch cartVm
            CartVM model = cart.FirstOrDefault(x => x.ProductId == productId);

            cart.Remove(model);
        }

        public ActionResult PaypalPartial()
        {
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            return PartialView(cart);
        }

        [HttpPost]
        public void PlaceOrder()
        {

            //fetch Cart content
            List<CartVM> cart = Session["cart"] as List<CartVM>;

            //fetch user name
            string username = User.Identity.Name;

            //declare number of order
            int orderId = 0;

            using(Db db = new Db())
            {
                //init OrderDTO
                OrderDTO orderDTO = new OrderDTO();
                //fetch user id
                var user = db.Users.FirstOrDefault(x => x.UserName == username);
                int userId = user.Id;
                //set orderDTO and save to db
                orderDTO.UserId = userId;
                orderDTO.CreateAt = DateTime.Now;

                db.Orders.Add(orderDTO);
                db.SaveChanges();

                //Fetch id sending order
                orderId = orderDTO.OrderId;

                //init OrderDetrails
                OrderDetailsDTO orderDetailsDTO = new OrderDetailsDTO();

                foreach (var item in cart)
                {
                    orderDetailsDTO.OrderId = orderId;
                    orderDetailsDTO.UserID = userId;
                    orderDetailsDTO.ProductId = item.ProductId;
                    orderDetailsDTO.Quantity = item.Quantity;

                    db.OrderDetails.Add(orderDetailsDTO);
                    db.SaveChanges();
                }
                
            }

            //sending email to Admin
            var client = new SmtpClient("smtp.mailtrap.io", 2525)
            {
                Credentials = new NetworkCredential("fc52bb2dd7aa79", "b99439a7fcc65c"),
                EnableSsl = true
            };
            client.Send("admin@example.com", "admin@example.com", "Nowe zamówienie", "Masz nowe zmówienie. NUmer zamówienia " + orderId);

            //reset Session
            Session["cart"] = null;

        }
    }


}

CmsShop/CmsShop/Controllers/PagesController.cs
using CmsShop.Models.Data;
using CmsShop.Models.ViewModels.Pages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CmsShop.Controllers
{
    public class PagesController : Controller
    {
        // GET: Index/{pages}
        public ActionResult Index(string page = "")
        {
            //string page = "" - describe default page(for example "home")

            //Set slug page
            //so if not declare by user ...
            if (page == "")
                page = "home";
            //Declare PageVm, PageDTO
            PageVM model;
            PageDTO dto;

            //check existing page
            using(Db db = new Db())
            {
                if(!db.Pages.Any(x => x.Slug.Equals(page)))               
                    //not existing case - redirect to default page(main page)
                    return RedirectToAction("Index", new { page = "" });
                
            }

            //fetch pageDTo
            using(Db db = new Db())
            {
                dto = db.Pages.Where(x => x.Slug == page).FirstOrDefault();
            }

            //set title page
            ViewBag.PageTitle = dto.Title;

            //CHeck if page has SIdeBar
            if(dto.HasSidebar == true)
                ViewBag.Sidebar = "Tak";
            
            else
                ViewBag.Sidebar = "Nie";

            

            //Initialization PageVm
            model = new PageVM(dto);


            return View(model);
        }

        public ActionResult PagesMenuPartial()
        {
            //declare PageVm
            List<PageVM> pageVMList;
            //fetch pages
            using (Db db = new Db())
            {
                pageVMList = db.Pages.ToArray()
                    .OrderBy(x => x.Sorting)
                    .Where(x => x.Slug != "home")
                    .Select(x => new PageVM(x)).ToList();
            }

            //return list of PageeVM
            return PartialView(pageVMList);
            
        }

        public ActionResult SidebarPartial()
        {
            //declare a model
            SidebarVM model;
            //initialization model
            using(Db db = new Db())
            {
                SidebarDTO dto = db.Sidebar.Find(1);
                model = new SidebarVM(dto);
            }

            //return partial with model
            return PartialView(model);
        }
    }
}

CmsShop/CmsShop/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CmsShop</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-topcancel">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">CmsShop</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Action("PagesMenuPartial", "Pages");
                    @if (Request.IsAuthenticated)
                    {
                        <li><a href="/account/logout">Wylogowanie</a></li>
                    }
                    else
                    {
                        if (ViewBag.Title == "Logowanie")
                        {
                            <li class="active"><a href="/account/login">Logowanie</a></li>
                        }
                        else
                        {
                            <li><a href="/account/login">Logowanie</a></li>
                        }

                    }
                    @if (Request.IsAuthenticated && User.IsInRole("User"))
                    {
                        if (ViewBag.Title == "Profil użytkownika")
                        {
                            //highlighting profile(When we on this profile in Bar)
                            <li class="active">@Html.Action("UserNavPartial", "Account", new { area = "" })</li>
                        }
                        else
                        {
                            <li>@Html.Action("UserNavPartial", "Account", new { area = "" })</li>
                        }

                    }
                </ul>

                @if (Request.IsAuthenticated && User.IsInRole("Admin"))  //check if user is login as Admin profile
                {
                    <ul class="navbar-collapse collapse navbar-right adminarea">
                        <!--if user is login on profile Admin its get link to Admin Panel-->
                        <li>@Html.ActionLink("Dashboard", "Index", "Dashboard", new { area = "Admin" }, null)</li>
                    </ul>

                }
                else //user is not loggin on Admin profile
                {
                    if (ViewBag.Title != "Koszyk szczegóły")
                    {
                        //redirect to Cart partial
                        <ul class="nav navbar-nav navbar-right">
                            @Html.Action("CartPartial", "Cart")
                        </ul>
                    }
                }

            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">

            @if (ViewBag.Title != "Utwórz konto" &&
               ViewBag.Title != "Logowanie" &&
               ViewBag.Title != "Profil uzytkownika" &&
               ViewBag.Title != "Zamowienia")
            {
                <div class="col-xs-12 col-md-2">
                    @Html.Action("CategoryMenuPartial", "Shop")
                </div>
            }


            @if (ViewBag.Title == "Profil uzytkownika")
            {
                <div class="col-xs-12 col-md-2">
                    <ul>
                        <li><a href="/account/orders">Moje Zamówienia</a></li>
                    </ul>
                </div>
            }

            @if (ViewBag.Title == "Zamowienia")
            {
                <div class="col-xs-12 col-md-2">
                    <ul>
                        <li><a href="/account/user-profile">Mój profil</a></li>
                    </ul>
                </div>
            }

            @if (ViewBag.Sidebar == "Tak")
            {
                <div class="col-xs-12 col-md-7">
                    @RenderBody()
                </div>
                <div class="col-xs-12 col-md-3">
                    @Html.Action("SidebarPartial", "Pages");
                </div>
            }
            else
            {

                <div class="col-xs-12 col-md-10">
                    @RenderBody()
                </div>
            }
        </div>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CmsShop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>